# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm2env < Formula
  desc ""
  homepage ""
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.5.0/ssm2env_1.5.0_darwin_amd64.tar.gz"
      sha256 "af8243b96f4f9f03105299e65db9d16241cea391b993f4516e454495598999bc"

      def install
        bin.install "ssm2env"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.5.0/ssm2env_1.5.0_darwin_arm64.tar.gz"
      sha256 "8909650aa59bb07c9a4c1a48d5a05ac26488e3332e5699e7b72f0fa4e4ecd2ca"

      def install
        bin.install "ssm2env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.5.0/ssm2env_1.5.0_linux_arm64.tar.gz"
      sha256 "4cf78ac7c026789726d68428524dd08c4da7aa64bc8461ff3566494ed4f55c28"

      def install
        bin.install "ssm2env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.5.0/ssm2env_1.5.0_linux_amd64.tar.gz"
      sha256 "4fd6b03a057fa413c19000d32cf97df2977d0601af6608ec88812e74f5e29e5f"

      def install
        bin.install "ssm2env"
      end
    end
  end
end
