# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm2env < Formula
  desc ""
  homepage ""
  version "1.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.3.1/ssm2env_1.3.1_darwin_amd64.tar.gz"
      sha256 "4f1c92b17a66418fd1d6d0ce33c7bb57c8f567e07ba2443ead76132bfe314b94"

      def install
        bin.install "ssm2env"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.3.1/ssm2env_1.3.1_darwin_arm64.tar.gz"
      sha256 "a52220e36995084614eb283eae1a9dc8088b4e1a0e24a84343b2bffd8ad66ca4"

      def install
        bin.install "ssm2env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.3.1/ssm2env_1.3.1_linux_arm64.tar.gz"
      sha256 "08acdf062e8610a5c807333aa41e4f5b6ee4f3e6f0f30ae60acb746df9ee78e9"

      def install
        bin.install "ssm2env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.3.1/ssm2env_1.3.1_linux_amd64.tar.gz"
      sha256 "2ff7e387f101ae063ce296ebbe9374afcaa3b6b09c2dfb7f46cc44b94100b801"

      def install
        bin.install "ssm2env"
      end
    end
  end
end
