# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm2env < Formula
  desc ""
  homepage ""
  version "1.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.4.0/ssm2env_1.4.0_darwin_arm64.tar.gz"
      sha256 "b36795ccc5e2f43af27688eaad1822e17ee0b1f7679835d7b3ceea3810d3d673"

      def install
        bin.install "ssm2env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.4.0/ssm2env_1.4.0_darwin_amd64.tar.gz"
      sha256 "d0a66a9747875c4483c91515721df1d120de4dc3a3b626f588538b818ecba235"

      def install
        bin.install "ssm2env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.4.0/ssm2env_1.4.0_linux_arm64.tar.gz"
      sha256 "1152ed4f7c39be9876397e72819dbef15eb49828f4d8752adea0695ad129951d"

      def install
        bin.install "ssm2env"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shopsmart/ssm2env/releases/download/v1.4.0/ssm2env_1.4.0_linux_amd64.tar.gz"
      sha256 "86765eba43160d951c6cb56c882a72255c7d1d43f1f123e217210e61533c6b8a"

      def install
        bin.install "ssm2env"
      end
    end
  end
end
